# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HereIAm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HereIAm

  target 'ReactNativeMaps' do
  # Pods for ReactNativeMaps
  pod 'GoogleMaps'
  end



  target 'HereIAmTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HereIAm-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HereIAm-tvOS

  target 'HereIAm-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
